version: "3.8"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend